server:
  port: 8761

#???? ???? ID? ???? ?
spring:
  application:
    name: discovery-service

#Discovery Service? ?????? ???? ??? ??
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    